normalize_markdown:
  - "tabs_to_spaces"
  - "normalize_list_spaces"
  - "remove_list_blank_lines"
  - "round_indentations_to_four"
  - "start_lists_with_dashes"
  - "replace_bold_lists_after_first_level_with_italicized"
  - "remove_bold_headings"
  - "add_new_line_after_headings"
  - "ensure_two_line_breaks_before_headings"
  - "add_new_line_after_bold_or_italicized_lines"
  - "add_new_line_before_lists"
  - "add_new_line_after_lists"
  - "add_new_line_after_paragraphs"
  - "remove_double_spaces"
  - "remove_blank_lines"
  - "remove_bold_headings_with_preceding_text"
  - "remove_line_breaks_surrounding_headings"
  - "remove_trailing_spaces"
  - "replace_left_single_smart_quote"
  - "replace_right_single_smart_quote"
  - "replace_left_double_smart_quote"
  - "replace_right_double_smart_quote"
  - "replace_ellipsis"
remove_bold_italics_backticks:
  - "protect_first_level_bold_list"
  - "protect_first_level_bold_list_tag"
  - "protect_subsequent_level_italicized_list_tag"
  - "protect_leading_asterisk"
  - "remove_inline_code"
  - "remove_remaining_bold"
  - "remove_remaining_italicized"
  - "restore_protected_bold"
  - "restore_protected_italicized"
  - "restore_leading_asterisk"
